name: Sample pipleline
on:
  push:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Unit test
        uses: actions/checkout@master
      - name: Test coverage
        uses: ./
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          annotations: failed tests
          test-script: npm run test:coverage
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master